name: Metrics
on:
  # Schedule daily updates(JST 00:00)
  schedule:
    - cron: "0 15 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KenCir/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: header, activity, community, repositories, metadata

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
